version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: "🔧 build"
    include: "scope"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "🔧 build"
    include: "scope"
