---
name: golangci-lint

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Build source code
      run: go build ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        only-new-issues: true